### ISSUE TITLE
Generate Acceptance Level Testcases

### ISSUE THREAD

**Issue by devsoftzz** [WebMetadataRetrieval/15-Web_Metadata_Retrieval#52]
- [x] Write test cases based on our business requirements and check whether our final product is meeting those requirements or not.

**Comment by Isha-Desai** [comment]
I was thinking of writing the basic functional requirements as components and then connecting it acceptance test cases. As there is too much repetition while writing an acceptance test case, so to avoid the same

**Comment by Isha-Desai** [comment]
Some of the points that I look to cover under the same is:

- [ ] Analysing the business Requirments
- [ ] Creation of test plan
- [ ] Identifying Test scenarios
- [ ] Create UAT test cases
- [ ] Preparation of Test Data (Production like data)
- [ ] Run the test cases
- [ ] Record the Results
- [ ] Confirm business objectives
