### ISSUE TITLE
Create API Documentation

### ISSUE THREAD

**Issue by devsoftzz** [WebMetadataRetrieval/15-Web_Metadata_Retrieval#8]

**Comment by Isha-Desai** [comment]
Completed API documentation--> by specifying the important steps required to generate the key.

**Comment by Isha-Desai** [comment]
Also displaying how the outcome looks like on successful execution and when an error is made.

**Comment by Isha-Desai** [comment]
Sorry, forgot to upload the doc. I have done the same now
